name: Build and deploy Node.js app to Azure Web App - occdevvsfcdla

on:
  push:
    branches:
      - develop
      - features/deployment
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "Log level: $LEVEL"
        env:
          LEVEL: ${{ github.event.inputs.logLevel }}
          
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: yarn install, build, and test
        run: |
          yarn install --network-timeout=30000
          yarn run build
          yarn run test
          
      - name: Zip artifact for deployment
        run: zip release.zip ./ -r 

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: release.zip
#           path: |
#              .
#              !./node_modules
#              !./packages/theme/node_modules


  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app
      - name: unzip artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'occdevvsfcdla'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_19DF8C32D3B34DECA5D935A85BE47AE7 }}
          package: .
